-- RESTORE RLS
-- Safety First!

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vve_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_membership_cache ENABLE ROW LEVEL SECURITY;
